syntax = "proto3";

option java_multiple_files = true;
option java_package="com.kvstore.grpc";

message WalRecord{
  enum OpType{
    PUT = 0;
    DEL = 1;
  }

  OpType type = 1;
  string key = 2;
  string value = 3;
}

message PutRequest{
  string key = 1;
  string value = 2;
}

message PutResponse{
  bool successful = 1;
}

message GetRequest{
  string key = 1;
}

message GetResponse{
  string value = 1;
  bool found = 2;
}

message AppendEntriesRequest{
  int32 term = 1;
  string leader_id = 2;
  int32 prev_log_index = 3;
  int32 prev_log_term = 4;
  repeated string entries = 5;
  int32 leader_commit_index = 6;
}

message AppendEntriesResponse{
  int32 term = 1;
  bool success = 2;
}

message RequestVoteRequest{
  int32 term = 1;
  string candidate_id = 2;
  int32 last_log_term = 3;
  int32 last_log_index = 4;
}

message RequestVoteResponse{
  int32 term = 1;
  bool vote_granted = 2;
}

service KVService{
  rpc put(PutRequest) returns (PutResponse);
  rpc get(GetRequest) returns (GetResponse);
  rpc appendEntries(AppendEntriesRequest) returns (AppendEntriesResponse);
  rpc requestVote(RequestVoteRequest) returns (RequestVoteResponse);
}